apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: review-dr-test
spec:
  host: reviewstest
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviewstest
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
  - route:
    - destination:
        host: reviews
        subset: v1
