apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: productpage-gw
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
    - "*"
  gateways:
    - productpage-gw
  http:
    - route:
       - destination:
           host: productpage

---

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: reviews-dr
spec:
  host: reviews
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
         host: reviews
         subset: v1
      weight: 50
    - destination:
         host: reviews
         subset: v3
      weight: 50

