#open httpbin though gw
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: foo
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: foo
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        port:
          number: 8000
        host: httpbin.foo.svc.cluster.local


---

apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway #JWT validation at ingress
  jwtRules:
  - issuer: "testing@secure.istio.io"  # if the token is available, try matching here. If no token. skip and move forward.
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.18/security/tools/jwt/samples/jwks.json"

---

### adding below authpolicy to make the JWT mandatory

#   apiVersion: security.istio.io/v1
#   kind: AuthorizationPolicy
#   metadata:
#     name: "frontend-ingress"
#     namespace: istio-system
#   spec:
#     selector:
#       matchLabels:
#         istio: ingressgateway
#     action: DENY  # toekn is mandatory
#     rules:
#     - from:
#       - source:
#           notRequestPrincipals: ["-"] # is no token(=no principle). Take - as the user


apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "frontend-ingress"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
    to:
    - operation:
        paths: ["/headers"] #authenticate only /headers
